---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7-browsers
    steps:
      - checkout
      - restore_cache:
          key: justdeps
      - run:
          name: Install Node deps
          command: |
            npm install
      - save_cache:
          key: justdeps
          paths:
            - node_modules
      - run:
          command: |
            ./node_modules/tape/bin/tape -r babel-register -r babel-polyfill test/*